services:
  - type: web
    name: notes-api-backend
    runtime: native
    rootDir: backend
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=10000